config/routes.rb
Rails.application.routes.draw do


  resources :farms, :reviews, :user

  resources :reviews

  devise_for :users, controllers: { registrations: "registrations"}

  root 'pages#home'

  get 'dashboard', to: 'pages#dashboard'

end

app/models/farm.rb
class Farm < ActiveRecord::Base
	validates_presence_of :name, :address, :latitude, :longitude

	geocoded_by :address
	#after_validation :geocode ### You're responsible for setting your own latitude, longitude

	has_many :reviews, dependent: :destroy

	def average_rating
		self.reviews.sum(:score) / reviews.size
	rescue ZeroDivisionError
		0
	end

	def self.search(search)
		if search
			# where(['name ILIKE ? OR address ILIKE ?', "%#{search}%", "%#{search}%"])
			near(search)
		else
			all
		end
	end



end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :farm

	validates_presence_of :score
	validates_presence_of :content

	after_save :calculate_average

	def calculate_average
		a = self.farm.average_rating
		self.farm.update_attributes(total_average_rating: a)
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_presence_of :name
  has_many :farms, dependent: :destroy
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
require 'ostruct'
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action do

  	if Rails.env.production?
  		@browser_location = request.location
	else
		defaults = {ip: "73.166.222.21",country_code: "US",country_name: "United States",region_code: "TX",region_name: "Texas",city: "Houston",zip_code: '77027',time_zone: "America/Chicago",latitude: 29.743,longitude: -95.445,metro_code: 618}
  		@browser_location = OpenStruct.new(defaults)
  	end
  end
end

app/controllers/farms_controller.rb
class FarmsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_farm, only: [:show, :edit, :update, :destroy]

  def index
    # 

    # Use me for a big map

    if params[:search].present?
      @farms = Farm.search(params[:search]).page(params[:page])
    else
      coords = [@browser_location.latitude, @browser_location.longitude]
      @farms = Farm.near(coords, 100).page(params[:page])
    end

    if @farms.first.present?
      @map_coordinates = [@farms.first.latitude, @farms.first.longitude].join(",")
    else
      coords = [@browser_location.latitude, @browser_location.longitude]
      @map_coordinates = coords.join(",")
    end
    # @farms = Farm.first.nearbys.page(params[:page])

    # 1: find the nearest farm and get nearbys
    # 2: figure out what's wrong with near

    # @farms = Farm.near( "4203 Montrose, Houston TX").page(params[:page])

  end


  def show
    @reviews = @farm.reviews
    if current_user
      @review = Review.new
    end
  end


  def new
    @farm = Farm.new
  end


  def edit
  end


  def create
    @farm = current_user.farms.new(farm_params)

      if @farm.save
        redirect_to @farm, notice: 'Farm was successfully created.' 
      else
        render :new
      end
  end

 
  def update
      if @farm.update(farm_params)
        redirect_to @farm, notice: 'Farm was successfully updated.'
      else
        render :edit
      end
  end


  def destroy
    @farm.destroy
      redirect_to farms_url, notice: 'Farm was successfully destroyed.'
  end

  # @farms = Farm.all
  # @hash = Gmaps4rails.build_markers(@farms) do |farm, marker|
  # marker.lat farm.latitude
  # marker.lng farm.longitude
  

  private
 
    def set_farm
      @farm = Farm.find(params[:id])
    end


    def farm_params
      params.require(:farm).permit(:name, :address, :website, :latitude, :longitude, :schedule)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :authenticate_user!, only: [:dashboard]

  def home
  	if current_user
  		redirect_to dashboard_path
  	end
  end

  def dashboard
  	@user = current_user
  	@farms = @user.farms
  	@reviews = @user.reviews 
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

	def sign_up_params
		params.require(:user).permit(:name, :email, :password)
	end

	def account_update_params
		params.require(:user).permit(:name, :email, :password, :current_password)		
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :authenticate_user!
	before_action :set_review, only: [:edit, :update, :destroy]

	def edit
		@farm = @review.farm
	end

	def create
		@review = current_user.reviews.new(review_params)

		if @review.save
			redirect_to farm_path(@review.farm), notice: 'Review was successfully created.'
		else
			redirect_to farm_path(@review.farm), notice: "Something went wrong"
		end
	end

	def update
		if @review.update(review_params)
			redirect_to farm_path(@review.farm), notice: 'Review was successfully updated.'
		else
			redirect_to farm_path(@review.farm), notice: "Something went wrong"
		end
	end

	def destroy
		@review.destroy
		redirect_to farm_path(@review.farm), notice: 'Review was successfully destroyed.'
	end

	private

	def set_review
		@review = Review.find(params[:id])
	end

	def review_params
		params.require(:review).permit(:content, :farm_id, :score)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/farms_helper.rb
module FarmsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/farms/_form.html.erb
<%= simple_form_for(@farm) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, required: true %>
    <%= f.input :address, required: true %>
    <%= f.input :website, required: true %>
    <%= f.input :schedule, required: true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/farms/edit.html.erb
<h1>Editing Farm</h1>

<%= render 'form' %>

<%= link_to 'Show', @farm %> |
<%= link_to 'Back', farms_path %>

app/views/farms/index.html.erb
 <div id="map"></div>

<h1>Listing Farmer's Markets <small><%= @farms.total_count %> Farms</small></h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Website</th>
      <th>Schedule</th>
      <th>Reviews</th>
    </tr>
  </thead>

  <tbody>
    <% @farms.each do |farm| %>
      <tr>
        <td><%= link_to farm.name, farm_path(farm) %></td>
        <td><%= farm.address %></td>
        <td><%= link_to farm.website, farm.website, :target => "_blank" %></td>
        <td><%= farm.schedule %></td>
        <td nowrap="nowrap"><div class="average_<%= farm.id %>"></div></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @farms %>

<br>
<% if current_user %>
<%= link_to "New Farmer's Markets", new_farm_path %>
<% end %>

<script type="text/javascript">
  
  <% @farms.each do |farm| %>
      $(".average_<%= farm.id %>").raty({
        starOn: "<%= image_path('star-on.png') %>",
        starOff: "<%= image_path('star-off.png') %>",
        score: <%= farm.total_average_rating %>,
        readOnly: true
      });
      <% end %>

</script>

<script>
$(window).ready(function() {

  window.map = L.map('map');

  L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
    attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
    maxZoom: 18,
    id: 'ingridhastings.bc26c7a2',
    accessToken: 'pk.eyJ1IjoiaW5ncmlkaGFzdGluZ3MiLCJhIjoiNDQyMGEyMWY1YTVkYTk1MGJlMzNlMDhkNTFjZmJkZGEifQ.QQFmYFRRPmjbDthM1xyHsg'
  }).addTo(window.map);


  window.map.setView([<%= @map_coordinates %>], 10);
  <% @farms.each do |farm| %>
  L.marker([<%= farm.latitude%> , <%= farm.longitude %>]).bindPopup("<b><%= farm.name %></b><br/><%= farm.address %>").addTo(map);
  <% end %>
})
</script>

app/views/farms/new.html.erb
<h1>New Farm</h1>

<%= render 'form' %>

<%= link_to 'Back', farms_path %>

app/views/farms/show.html.erb
<div class="row">
  <div class="col-md-3">
    <h3><%= @farm.name %></h3>
    <div class="average"> </div>
    
    <p>
      <strong>Address:</strong>
      <%= @farm.address %>
    </p>
    
    <p>
      <strong>Website:</strong>
      <%= link_to @farm.website, @farm.website, :target => "_blank"  %>
    </p>    

    <p>
      <strong>Schedule:</strong>
      <%= @farm.schedule %>
    </p>


    <div id="map-canvas" style="width: 230px; height: 230px;"></div>

  </div>

  <div class="col-md-9">
    <h3>Reviews by People</h3>
    <% if current_user %>
    <h5>New Review</h5>
    <%= render "reviews/form" %>
    <h5>All Reviews</h5>
    <%= render @reviews %>
    <% end %>
  </div>




  <script type="text/javascript">
  function initialize() {
    var mycenter = { lat: <%= @farm.latitude %>, lng: <%= @farm.longitude %> }
    var mapOptions = {
      center: mycenter,
      zoom: 8
    };
    var map = new google.maps.Map(document.getElementById('map-canvas'),
      mapOptions);
    var marker = new google.maps.Marker({
      position: mycenter, 
      map: map
    });
  }
  google.maps.event.addDomListener(window, 'load', initialize);
  
  <% @reviews.each do |review| %>
  
  $(".score_<%= review.id %>").raty({
    starOn: "<%= image_path('star-on.png') %>",
    starOff: "<%= image_path('star-off.png') %>",
    score: <%= review.score %>,
    readOnly: true
  });

  <% end %>

  $(".average").raty({
    starOn: "<%= image_path('star-on.png') %>",
    starOff: "<%= image_path('star-off.png') %>",
    score: <%= @farm.total_average_rating %>,
    readOnly: true
  }); 
  
  </script>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Get Real Food", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Farmer's Markets", farms_path %></li>    
      </ul>


      <%= form_tag farms_path, method: "get", class: "navbar-form navbar-left" do %>
        <div class="form-group">
        <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Type a farmer's market" %>
        </div>
        <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
      <% end %>


      <ul class="nav navbar-nav navbar-right">        
        <% if current_user %>
        <li><%= link_to "Dashboard", dashboard_path %></li>
        <li><%= link_to "Settings", edit_user_registration_path %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Login", new_user_session_path %></li>
        <li><%= link_to "Signup", new_user_registration_path %></li>
        <% end %>        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

 
  <title>GetRealFood</title>
 
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.css" />

 <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.js"></script>
 

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCRgDjHE5gMxmn9KQaYkRPQKLql1_e_kK0">
  </script>

</head>
<body>

<%= render 'layouts/header' %>

<% flash.each do |type, message| %>
<div class="alert alert-info fade-in">
<button class="close" data-dismiss="alert">x</button>
<%= message %>
</div>
<% end %>

<% if current_page?(root_path) %>
	<div class="landing">
<% else %>
	<div class="container">
	<% end %>

<%= yield %>
</div>

</body>
</html>

app/views/pages/dashboard.html.erb
<div class="row">

<!-- Profile info -->
	<div class="col-md-2">
	<h3><%= @user.name %></h3>
	<%= gravatar_tag @user.email, size: 150 %>
	</div>

<!-- Farms -->
	<div class="col-md-5">
	<h3>My Farmer's Markets</h3>

	<table class="table">

	<thead>
		<tr>
		<th>Name</th>
		<th>Created</th>
		<th></th>
		</tr>
	</thead>

	<tbody>

	<% @farms.each do |farm| %>

		<tr>
			<td><%= link_to farm.name, farm_path(farm) %></td>
			<td><%= time_ago_in_words(farm.created_at) %> ago</td>
			<td><%= link_to "Edit", edit_farm_path(farm) %> | <%= link_to "Destroy", farm_path(farm), method: :delete %></td>
		</tr>

	<% end %>

	</tbody>

	</table>
	<%= link_to "New Farm", new_farm_path %>

	</div>

<!-- Reviews -->
	<div class="col-md-5">
		<h3>My Reviews</h3>
		<table class="table">
			<thead>
				<tr>
					<th>Farm</th>
					<th>Created</th>
					<th>Rating</th>
					<th></th>
				</tr>
			</thead>

			<tbody>
				<% @reviews.each do |review| %>
					<tr>
						<td><%= link_to review.farm.name, farm_path(review.farm) %></td>
						<td><%= time_ago_in_words(review.created_at) %> ago</td>
						<td><div class="score_<%= review.id %>"></div></td>
						<td><%= link_to "Edit", edit_review_path(review) %> | <%= link_to "Destroy", review_path(review), method: :delete %></td>
					</tr>

				<% end %>
			</tbody>
		</table>
	</div>

</div>

<script type="text/javascript">
	 <% @reviews.each do |review| %>
      $(".score_<%= review.id %>").raty({
        starOn: "<%= image_path('star-on.png') %>",
        starOff: "<%= image_path('star-off.png') %>",
        score: <%= review.score %>,
        readOnly: true
      });
      <% end %>
</script>

app/views/pages/home.html.erb
<div class="text-center landing_title">
	<%= link_to "Find a local Farmer's Market", farms_path, class: "btn btn-default btn-lg btn-landing" %>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for(@review) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :content, required: true %>
    <%= f.hidden_field :farm_id, required: true, :value => @farm.id %>
    <%= f.hidden_field :score, required: true %>
    <div class="score"></div>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<script>
$(".score").raty({
	starOn: "<%= image_path('star-on.png') %>",
	starOff: "<%= image_path('star-off.png') %>",
	target: "#review_score",
	targetKeep: true,
	targetType: "number"

});
</script>

app/views/reviews/_review.html.erb
<p><%= gravatar_tag review.user.email, size: 20 %> <%= review.content %> by <%= review.user.name %><div class="score_<%= review.id %>"></div></p>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= render "form" %>